name = "hex-row-reduce-mathlib"
defaultTargets = ["HexRowReduceMathlib"]

[[require]]
name = "HexRowReduce"
git = "https://github.com/kim-em/hex-row-reduce.git"
rev = "94b9e0043b9ba8b768b3fa9a93d7cd6d48a3c8f3"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/kim-em/hex-matrix-mathlib.git"
rev = "402c2a9b7ddc7b2d0b87f2fad26a1b5ecd639bd0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "HexRowReduceMathlib"
