name = "hex-row-reduce-mathlib"
defaultTargets = ["HexRowReduceMathlib"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "49d4eb822ce66aa14b18c2472c18848a2411792d"

[[require]]
name = "HexRowReduce"
git = "https://github.com/kim-em/hex-row-reduce.git"
rev = "962bf360dd394acd319ab8f2d632d6809cbc1340"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/kim-em/hex-matrix-mathlib.git"
rev = "ad3189f98d3bc9001b11b229b1b0304f8d284ace"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0-rc1-patch1"

[[lean_lib]]
name = "HexRowReduceMathlib"
