name = "hex-row-reduce-mathlib"
defaultTargets = ["HexRowReduceMathlib"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "f1580d28c2e9ff9e8d4d7cdef9dccbaa17780b03"

[[require]]
name = "HexRowReduce"
git = "https://github.com/kim-em/hex-row-reduce.git"
rev = "922d066445a6a9e2deb2cad5cca099b2dad2c98e"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/kim-em/hex-matrix-mathlib.git"
rev = "a712810da16f8b2d0322d79c0deb64c1290a4ca9"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0-rc1-patch1"

[[lean_lib]]
name = "HexRowReduceMathlib"
